# Generated by Django 6.0.7 on 2026-07-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BackfillJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("worker", models.CharField(default="", max_length=64)),
                ("started_ms", models.BigIntegerField(default=0)),
                ("pages_fetched", models.IntegerField(default=0)),
                ("errors", models.IntegerField(default=0)),
                ("finished", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "cid",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(default="", max_length=64)),
                (
                    "status",
                    models.CharField(db_index=True, default="active", max_length=12),
                ),
                ("total_recipients", models.IntegerField(default=0)),
                ("n_pages", models.IntegerField(default=0)),
                ("seeded_at_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_rid", models.CharField(max_length=32, unique=True)),
                ("campaign_cid", models.CharField(max_length=16)),
                ("page_id", models.CharField(max_length=16)),
                ("message_id", models.CharField(max_length=64)),
                ("sent_at_ms", models.BigIntegerField(default=0)),
                ("enqueued_first_ms", models.BigIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["sent_at_ms"], name="sendlog_sentat_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookInboxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_key", models.CharField(max_length=32, unique=True)),
                ("status", models.CharField(default="pending", max_length=12)),
                ("attempts", models.SmallIntegerField(default=0)),
                ("next_due_ms", models.BigIntegerField(default=0)),
                ("payload", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "next_due_ms"], name="webhook_claim_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "rid",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
                ("page_id", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "pending"),
                            ("retry", "retry"),
                            ("queued", "queued"),
                            ("sending", "sending"),
                            ("sent", "sent"),
                            ("failed", "failed"),
                            ("skipped", "skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("attempts", models.SmallIntegerField(default=0)),
                ("next_due_ms", models.BigIntegerField(default=0)),
                ("lease_until_ms", models.BigIntegerField(default=0)),
                ("enqueued_first_ms", models.BigIntegerField(default=0)),
                ("sent_at_ms", models.BigIntegerField(default=0)),
                ("sent_flag", models.BooleanField(default=False)),
                ("lock_until_ms", models.BigIntegerField(default=0)),
                ("last_attempt_ms", models.BigIntegerField(default=0)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign", "status", "next_due_ms"],
                        name="recip_claim_due_idx",
                    ),
                    models.Index(
                        fields=["campaign", "status", "lease_until_ms"],
                        name="recip_claim_lease_idx",
                    ),
                    models.Index(fields=["sent_flag"], name="recip_sentflag_idx"),
                    models.Index(fields=["sent_at_ms"], name="recip_sentat_idx"),
                ],
            },
        ),
    ]
